### ISSUE TITLE
Extension file in Readme file is outdated.

### ISSUE THREAD

**Issue by nickcheng** [wfarr/dotjs.safariextension#3]

**Comment by holman** [comment]
Most def.

Signing up to be an Apple™ Certified™ Safari™™ Developer™ and getting my Official™ Developer™ Certificate™ let me build it locally with the latest from defunkt/dotjs. Would be great to get a new extension pushed, though.

**Comment by wfarr** [comment]
@holman Since you've got a working build, I've added you as a collab to the repo. Go HaaM.

**Comment by holman** [comment]
Can I just add my extension? Is there anything weird to adding it directly to the repo?

**Comment by wfarr** [comment]
I think that should work fine.

**Comment by holman** [comment]
a8f66c070ec9ed8f3ef160a8386e489cf8931b4f.
